services:
  postgres:
    image: postgres:16
    container_name: lms_postgres
    environment:
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
      POSTGRES_DB: lms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms_user"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
    driver: local
